// src/resources/js/runtime/vue/NativeCell.vue
<script setup>
import NativeAvatar from './NativeAvatar.vue';
import { cellText, dateLabel } from '../shared.js';
defineProps({ user: Object, column: Object, state: Object, store: Object });
</script>

<template>
    <NativeAvatar v-if="column.type === 'avatar'" :avatar="user.avatar"/>
    <dl v-else-if="column.type === 'activity'" class="lu-details">
        <div><dt>{{ state.page.labels.last_login_at }}</dt><dd><time v-if="user.activity?.last_login_at" :datetime="user.activity.last_login_at">{{ dateLabel(user.activity.last_login_at, state.page) }}</time><span v-else>{{ state.page.labels.no_logins }}</span></dd></div>
        <template v-for="key in ['device', 'os', 'browser', 'ip_address']" :key="key"><div v-if="user.activity?.[key]"><dt>{{ state.page.labels[key] }}</dt><dd>{{ user.activity[key] }}</dd></div></template>
    </dl>
    <time v-else-if="column.type === 'date' && cellText(user, column)" :datetime="cellText(user, column)">{{ dateLabel(cellText(user, column), state.page) }}</time>
    <a v-else-if="column.key === 'name' && user.urls?.show" :href="user.urls.show" @click.prevent="store.navigate(user.urls.show)">{{ user.name }}</a>
    <a v-else-if="column.key === 'email' && column.linked" :href="'mailto:' + user.email">{{ user.email }}</a>
    <span v-else-if="column.type === 'presence'" :class="['lu-badge', user.activity?.online ? 'lu-online' : '']">{{ user.activity?.online ? state.page.labels.online : state.page.labels.offline }}</span>
    <span v-else>{{ cellText(user, column) }}</span>
</template>

// src/resources/js/runtime/svelte/NativeCell.svelte
<script>
    import NativeAvatar from './NativeAvatar.svelte';
    import { cellText, dateLabel } from '../shared.js';
    let { user, column, state, store } = $props();
    const text = $derived(cellText(user, column));
</script>

{#if column.type === 'avatar'}<NativeAvatar avatar={user.avatar}/>
{:else if column.type === 'activity'}
    <dl class="lu-details"><div><dt>{state.page.labels.last_login_at}</dt><dd>{#if user.activity?.last_login_at}<time datetime={user.activity.last_login_at}>{dateLabel(user.activity.last_login_at, state.page)}</time>{:else}{state.page.labels.no_logins}{/if}</dd></div>{#each ['device', 'os', 'browser', 'ip_address'] as key}{#if user.activity?.[key]}<div><dt>{state.page.labels[key]}</dt><dd>{user.activity[key]}</dd></div>{/if}{/each}</dl>
{:else if column.type === 'date' && text}<time datetime={text}>{dateLabel(text, state.page)}</time>
{:else if column.key === 'name' && user.urls?.show}<a href={user.urls.show} onclick={event => { event.preventDefault(); store.navigate(user.urls.show); }}>{user.name}</a>
{:else if column.key === 'email' && column.linked}<a href={'mailto:' + user.email}>{user.email}</a>
{:else if column.type === 'presence'}<span class={'lu-badge ' + (user.activity?.online ? 'lu-online' : '')}>{user.activity?.online ? state.page.labels.online : state.page.labels.offline}</span>
{:else}{text}{/if}
